// <auto-generated />
using Application7.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Application7.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Application7.Web.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Application7.Web.Models.Guest", b =>
                {
                    b.Property<int>("GuestId")
                        .HasColumnType("int");

                    b.Property<string>("GuestName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("GuestId");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("Application7.Web.Models.MenuItem", b =>
                {
                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("MenuItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<short>("NumberOfPlates")
                        .HasColumnType("smallint");

                    b.HasKey("MenuItemId");

                    b.HasIndex("CategoryId");

                    b.ToTable("MenuItems");
                });

            modelBuilder.Entity("Application7.Web.Models.OrderInformation", b =>
                {
                    b.Property<int>("OrderInformationId")
                        .HasColumnType("int");

                    b.Property<int>("OrderMenuId")
                        .HasColumnType("int");

                    b.HasKey("OrderInformationId");

                    b.HasIndex("OrderMenuId");

                    b.ToTable("OrderInformation");
                });

            modelBuilder.Entity("Application7.Web.Models.OrderMenu", b =>
                {
                    b.Property<int>("OrderMenuId")
                        .HasColumnType("int");

                    b.Property<int>("GuestId")
                        .HasColumnType("int");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<string>("OrderMenuName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderMenuId");

                    b.HasIndex("GuestId");

                    b.HasIndex("MenuItemId");

                    b.ToTable("OrderMenus");
                });

            modelBuilder.Entity("Application7.Web.Models.MenuItem", b =>
                {
                    b.HasOne("Application7.Web.Models.Category", "Category")
                        .WithMany("MenuItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Application7.Web.Models.OrderInformation", b =>
                {
                    b.HasOne("Application7.Web.Models.OrderMenu", "OrderMenu")
                        .WithMany("OrderInformation")
                        .HasForeignKey("OrderMenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Application7.Web.Models.OrderMenu", b =>
                {
                    b.HasOne("Application7.Web.Models.Guest", "Guest")
                        .WithMany("OrderMenu")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Application7.Web.Models.MenuItem", "MenuItem")
                        .WithMany("OrderMenus")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
